apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-demo
spec:
  description: |
    this is a sample.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: cat-readme
    #runAfter: ["fetch-repo"]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      steps:
      - image: bash
        script: |
          #!/usr/bin/env bash
          cat $(workspaces.source.path)/go.mod
          pwd
          ls -lsa
  - name: code-build
    taskRef:
      name: golang-build
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: package
      value: samples
  - name: docker-build
    taskRef:
      name: docker-build
    params:
    - name: image
      value: localhost:5000/nocode
    workspaces:
    - name: source
      workspace: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-demo-run
spec:
  pipelineRef:
    name: clone-build-demo
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
  params:
  - name: repo-url
    value: https://github.com/waxiangzi/samples.git
  - name: branch-name
    value: master