apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-output
spec:
  params:
    - name: package
      type: string
  steps:
    - name: write-message
      image: alpine
      script: |
        #!/usr/bin/env sh
        set -xe
        echo $(params.package)! > $(workspaces.messages.path)/message
        cat $(workspaces.messages.path)/message
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee $(results.current-date-unix-timestamp.path)
        ls $(results.current-date-human-readable.path)
    - name: print-date-human-readable
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date | tee $(results.current-date-human-readable.path)
        ls $(results.current-date-human-readable.path)
    - name: results
      image: bash:latest 
      script: |
        ls -lsa /workspace/

  workspaces:
    - name: messages
      description: The folder where we write the message to
      mountPath: /custom/path/relative/to/root
  results:
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
    - name: current-date-human-readable
      description: The current date in human readable format

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-output-
spec:
  taskRef:
    name: test-output
  workspaces:
    - name: messages
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
  params:
  - name: package
    value: github.com/tektoncd/pipeline