apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-wordpress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
#    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: demo-wordpress.ppe1.iotsoft.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-wordpress
            port:
              number: 80
